package com.cattle.enums;

public enum BovineEventType {
    COMPRA, SEGUIMIENTO, BANO_GARRAPATAS, DESPARASITACION, MONTA,
    VACUNACION, TRATAMIENTO, PESAJE, INSEMINACION, DIAGNOSTICO_PRENEZ,
    PARTO, ABORTO, DESTETE, SECADO, PRODUCCION_LECHE,
    CASTRACION, DESCORNE, MARCACION, TRASLADO,
    VENTA, MUERTE, OBSERVACION
}
